### ISSUE TITLE
Cannot create enum type

### ISSUE THREAD

**Issue by trungtin** [gajus/slonik#131]
I want to create an enum with a list of strings.
Maybe I'm missing something here, but this
```
pool.query(sql`CREATE TYPE state AS ENUM (${'in'}, ${'out'})`) // user literal 'in' and 'out' here as an example
```

produce this
```
{ sql: 'CREATE TYPE "state3" AS ENUM ($1, $2)',
  values: [ 'a', 'b' ] }
```
at here https://github.com/gajus/slonik/blob/1ec5326171fa79135db93f92d35c5f8c628eb7fd/src/routines/executeQuery.js#L94-L96

In the end, it results in an error at `$1`

**Comment by gajus** [comment]
Please turn on logging and share logs.

https://github.com/gajus/slonik#logging

**Comment by trungtin** [comment]
```
{"context":{"package":"slonik","poolId":"01DVA7TD07ZWV1N2AMBSMXSM6H","connectionId":"01DVA7V5YM51YJKNT0X40K2P1T","transactionId":"01DVA7V5YM8FXNRWDKQZ8M0NQZ","queryId":"01DVA7V6546RWWAGMPMFHNA1RN","logLevel":20,"sql":"CREATE TYPE \"state\" AS ENUM ($1, $2)","stackTrace":[...],"values":["a","b"]},"message":"executing query","sequence":8,"time":1575523031206,"version":"1.0.0"}
{"context":{"package":"slonik","poolId":"01DVA7TD07ZWV1N2AMBSMXSM6H","connectionId":"01DVA7V5YM51YJKNT0X40K2P1T","transactionId":"01DVA7V5YM8FXNRWDKQZ8M0NQZ","queryId":"01DVA7V6546RWWAGMPMFHNA1RN","logLevel":50,"error":{"name":"error","length":91,"severity":"ERROR","code":"42601","position":"30","file":"scan.l","line":"1134","routine":"scanner_yyerror","message":"syntax error at or near \"$1\"","stack":"error: syntax error at or near \"$1\"\n    at Connection.parseE (/.../node_modules/slonik/node_modules/pg/lib/connection.js:606:11)\n    at Connection.parseMessage (/.../node_modules/slonik/node_modules/pg/lib/connection.js:403:19)\n    at Socket.<anonymous> (/.../node_modules/slonik/node_modules/pg/lib/connection.js:123:22)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at Socket.Readable.push (_stream_readable.js:219:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)"}},"message":"execution routine produced an error","sequence":9,"time":1575523031211,"version":"1.0.0"}
{"context":{"package":"slonik","poolId":"01DVA7TD07ZWV1N2AMBSMXSM6H","connectionId":"01DVA7V5YM51YJKNT0X40K2P1T","transactionId":"01DVA7V5YM8FXNRWDKQZ8M0NQZ","queryId":"01DVA7V6546RWWAGMPMFHNA1RN","logLevel":50,"error":{"name":"error","length":91,"severity":"ERROR","code":"42601","position":"30","file":"scan.l","line":"1134","routine":"scanner_yyerror","message":"syntax error at or near \"$1\"","stack":"error: syntax error at or near \"$1\"\n    at Connection.parseE (/.../node_modules/slonik/node_modules/pg/lib/connection.js:606:11)\n    at Connection.parseMessage (/.../node_modules/slonik/node_modules/pg/lib/connection.js:403:19)\n    at Socket.<anonymous> (/.../node_modules/slonik/node_modules/pg/lib/connection.js:123:22)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at Socket.Readable.push (_stream_readable.js:219:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)"}},"message":"query execution produced an error","sequence":10,"time":1575523031212,"version":"1.0.0"}
{"context":{"package":"slonik","poolId":"01DVA7TD07ZWV1N2AMBSMXSM6H","connectionId":"01DVA7V5YM51YJKNT0X40K2P1T","transactionId":"01DVA7V5YM8FXNRWDKQZ8M0NQZ","logLevel":50,"error":{"name":"error","length":91,"severity":"ERROR","code":"42601","position":"30","file":"scan.l","line":"1134","routine":"scanner_yyerror","message":"syntax error at or near \"$1\"","stack":"error: syntax error at or near \"$1\"\n    at Connection.parseE (/.../node_modules/slonik/node_modules/pg/lib/connection.js:606:11)\n    at Connection.parseMessage (/.../node_modules/slonik/node_modules/pg/lib/connection.js:403:19)\n    at Socket.<anonymous> (/.../node_modules/slonik/node_modules/pg/lib/connection.js:123:22)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at Socket.Readable.push (_stream_readable.js:219:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)"}},"message":"rolling back transaction due to an error","sequence":11,"time":1575523031216,"version":"1.0.0"}
{"context":{"package":"slonik","poolId":"01DVA7TD07ZWV1N2AMBSMXSM6H","logLevel":20,"processId":18455,"stats":{"idleConnectionCount":0,"totalConnectionCount":1,"waitingRequestCount":0}},"message":"client connection is closed and removed from the client pool","sequence":12,"time":1575523031218,"version":"1.0.0"}
{"context":{"package":"slonik","poolId":"01DVA7TD07ZWV1N2AMBSMXSM6H","connectionId":"01DVA7V5XKJPNSHG6EGHY8VZDF","transactionId":"01DVA7V5Y3T0PBMDZP566PCCBZ","logLevel":50,"error":{"name":"error","length":91,"severity":"ERROR","code":"42601","position":"30","file":"scan.l","line":"1134","routine":"scanner_yyerror","message":"syntax error at or near \"$1\"","stack":"error: syntax error at or near \"$1\"\n    at Connection.parseE (/.../node_modules/slonik/node_modules/pg/lib/connection.js:606:11)\n    at Connection.parseMessage (/.../node_modules/slonik/node_modules/pg/lib/connection.js:403:19)\n    at Socket.<anonymous> (/.../node_modules/slonik/node_modules/pg/lib/connection.js:123:22)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at Socket.Readable.push (_stream_readable.js:219:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)"}},"message":"rolling back transaction due to an error","sequence":13,"time":1575523031222,"version":"1.0.0"}
{"context":{"package":"slonik","poolId":"01DVA7TD07ZWV1N2AMBSMXSM6H","logLevel":20,"processId":18454,"stats":{"idleConnectionCount":0,"totalConnectionCount":0,"waitingRequestCount":0}},"message":"client connection is closed and removed from the client pool","sequence":14,"time":1575523031222,"version":"1.0.0"}
[2019-12-05 05:17:11.224 +0000] ERROR (error/39478 on X.local): syntax error at or near "$1"
    error: syntax error at or near "$1"
        at Connection.parseE (/.../node_modules/slonik/node_modules/pg/lib/connection.js:606:11)
        at Connection.parseMessage (/.../node_modules/slonik/node_modules/pg/lib/connection.js:403:19)
        at Socket.<anonymous> (/.../node_modules/slonik/node_modules/pg/lib/connection.js:123:22)
        at Socket.emit (events.js:182:13)
        at Socket.EventEmitter.emit (domain.js:442:20)
        at addChunk (_stream_readable.js:283:12)
        at readableAddChunk (_stream_readable.js:264:11)
        at Socket.Readable.push (_stream_readable.js:219:10)
        at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
[2019-12-05 05:17:11.227 +0000] ERROR (39478 on X.local): Unhandled exception occurred
{ error: syntax error at or near "$1"
    at Connection.parseE (/.../node_modules/slonik/node_modules/pg/lib/connection.js:606:11)
    at Connection.parseMessage (/.../node_modules/slonik/node_modules/pg/lib/connection.js:403:19)
    at Socket.<anonymous> (/.../node_modules/slonik/node_modules/pg/lib/connection.js:123:22)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  name: 'error',
  length: 91,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '30',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1134',
  routine: 'scanner_yyerror' }
```

**Comment by trungtin** [comment]
Also, I could create the enum from `psql` like this. 
`psql -v v1="'Hello'" db`
`db=# CREATE TYPE state AS ENUM (:v1)`
So I think this use-case is something PostgreSQL supported

**Comment by trungtin** [comment]
Actually this is a problem with `pg`, not `slonik`. I will create the issue over there
