### ISSUE TITLE
Wrong typings for createPool arguments

### ISSUE THREAD

**Issue by SeedyROM** [gajus/slonik#157]
The types currently specify that createPool's first argument can be either a string or an object that describes the postgres connection.

## Expected Behavior

Create pool should accept either a string **or** a configuration object as specified in the types here:
```ts
export function createPool(
    connectionConfiguration: DatabaseConfigurationType,
    clientUserConfiguration?: ClientConfigurationInputType
): DatabasePoolType;

...

export type DatabaseConfigurationType =
    | string
    | {
        database?: string;
        host?: string;
        idleTimeoutMillis?: number;
        max?: number;
        password?: string;
        port?: number;
        user?: string;
    };
```

## Current Behavior
createPool only accepts strings

https://github.com/gajus/slonik/blob/master/src/factories/createPool.js#L22

## Possible Solution
Not sure in this case, confused why the types would reflect a feature that doesn't exist. Is it possible to accept a valid pool configuration just like in `node-postgres`

## Steps to Reproduce
```ts
const pool = createPool({host: 'localhost:5432', etc...})
```

## Logs
```
  if(str.charAt(0) === '/') {
         ^
TypeError: str.charAt is not a function
    at parse (/home/rombus/Workspace/amberdata/timeseries-kafka-consumer/node_modules/slonik/node_modules/pg-connection-string/index.js:13:10)
    at createPoolConfiguration (/home/rombus/Workspace/amberdata/timeseries-kafka-consumer/node_modules/slonik/src/factories/createPoolConfiguration.js:14:29)
    at Object.createPool (/home/rombus/Workspace/amberdata/timeseries-kafka-consumer/node_modules/slonik/src/factories/createPool.js:33:29)
    at Object.<anonymous> (/home/rombus/Workspace/amberdata/timeseries-kafka-consumer/src/index.ts:25:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.m._compile (/home/rombus/Workspace/amberdata/timeseries-kafka-consumer/node_modules/ts-node/src/index.ts:814:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/rombus/Workspace/amberdata/timeseries-kafka-consumer/node_modules/ts-node/src/index.ts:817:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

```

**Comment by gajus** [comment]
This is bug in TypeScript types. They are not hosted here.
