### ISSUE TITLE
How do I insert multiple records in my database using Slonik?

### ISSUE THREAD

**Issue by amite** [gajus/slonik#219]
I am a front end developer and this is my first time using Slonik.

I want to know how I can make this query dynamic by inserting the data (which is hardcoded) using function parameters:

```js
const addMany = async (connection = slonik) => {
  const useResult = await connection.query(sql`
    INSERT into 
      users (username, email) 
    VALUES 
      ('amite', 'amite@gmail.com'),
      ('nilesh', 'nil@gmail.com'),
      ('nikhil', 'nik@gmail.com')
      RETURNING *;
  `);

  return useResult;
};
```

Do I need to create tuples using string concatenation?

```js
      ('amite', 'amite@gmail.com'),
      ('nilesh', 'nil@gmail.com'),
      ('nikhil', 'nik@gmail.com')
```

What I have tried so far is:

```js
const addManyUsers = async(connection = slonik) => {
  const keys = [
    'username', 'email'
  ];
  
  const values = [
    ['nilesh', 'bailey'],
    ['nilesh@gmail.com', 'bailey@gmail.com']
  ]
  
  const identifiers = keys.map((key) => {
    return sql.identifier([key]);
  });
  
  const query = sql`
    INSERT INTO users
      (${sql.join(identifiers, sql`, `)})
    VALUES
      (${sql.unnest(values, sql`, `)})
    RETURNING *
  `
  const records = await connection.query(query)
  return records
}
```
When I run this I get the error:

```
(node:5975) UnhandledPromiseRejectionWarning: Error: **Column types length must match tuple member length.**
    at Object.createUnnestSqlFragment (/Users/shreekant/Documents/code/node/postgres-starter/node_modules/slonik/dist/sqlFragmentFactories/createUnnestSqlFragment.js:29:19)
    at Object.createSqlTokenSqlFragment (/Users/shreekant/Documents/code/node/postgres-starter/node_modules/slonik/dist/factories/createSqlTokenSqlFragment.js:27:39)
    at sql (/Users/shreekant/Documents/code/node/postgres-starter/node_modules/slonik/dist/factories/createSqlTag.js:39:65)
    at addManyUsers (/Users/shreekant/Documents/code/node/postgres-starter/app/models/db.js:58:20)
    at Object.<anonymous> (/Users/shreekant/Documents/code/node/postgres-starter/app/models/db.js:72:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5975) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5975) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

What am I doing wrong?

**Comment by gajus** [comment]
There is an example in the documentation

https://github.com/gajus/slonik#slonik-recipes-inserting-large-number-of-rows

**Comment by amite** [comment]
@gajus I tried this example. But I can't get it to run. What does ` INSERT INTO (foo, bar, baz)` mean? Are `foo, bar, baz` tables? I am really sorry. This is really confusing. How do I insert into my users table?

**Comment by gajus** [comment]
This isn't Slonik question.

Postgres documentation will be more helpful.

https://www.postgresql.org/docs/current/sql-insert.html

**Comment by amite** [comment]
I did manage to figure it out. Just leaving the answer here for posterity: https://stackoverflow.com/questions/64585026/how-do-i-insert-multiple-records-into-my-postgres-database-using-slonik/64591158#64591158

**Comment by mmkal** [comment]
@gajus it does look like the example is slightly off - shouldn't it be `insert into sometable (...)` rather than `insert into (...)` as it is now?

**Comment by gajus** [comment]
> @gajus it does look like the example is slightly off - shouldn't it be insert into sometable (...) rather than insert into (...) as it is now?

Good catch.
