### ISSUE TITLE
Slonik errors missing original error line numbers / stack traces

### ISSUE THREAD

**Issue by cyrieu** [gajus/slonik#261]
Slonik is great, but I've noticed that whenever an Error is thrown, e.g. a Data Integrity error, all I see is 
`
[0] DataIntegrityError: Query returns an unexpected result.
[0]     at one (/node_modules/slonik/src/connectionMethods/one.js:41:11)
[0]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[0]     at createConnection (//node_modules/slonik/src/factories/createConnection.js:153:14)
`
And it doesn't tell me where in my code the error happened.

## Expected Behavior
I expect see the line number of where this error happened in my code.

## Current Behavior
Only a Slonik Error is displayed and the stack trace is from the node_modules file.

## Possible Solution
Is it possible to preserve the original stack trace?

## Steps to Reproduce
`
try {
  await pool.query(sql"DATA INTEGRITY ERROR QUERY");
} catch (e) {
  console.error(e);
}
`

**Comment by gajus** [comment]
You will need to enable Stack trace capturing.

https://github.com/gajus/slonik#capture-stack-trace
