### ISSUE TITLE
TypeError: connectionHandler is not a function

### ISSUE THREAD

**Issue by vjpr** [gajus/slonik#280]
With ROAR logs.

```
{"context":{"package":"slonik","poolId":"ndWsfTZoSseGAcqQuHCzzQ-0","logLevel":20},"message":"pg-native module is not found","sequence":0,"time":1622298366081,"version":"1.0.0"}
{"context":{"package":"slonik","poolId":"ndWsfTZoSseGAcqQuHCzzQ-0","logLevel":30},"message":"using JavaScript bindings; pg-native not found","sequence":1,"time":1622298366082,"version":"1.0.0"}
{"context":{"package":"slonik","poolId":"ndWsfTZoSseGAcqQuHCzzQ-0","logLevel":20,"processId":19123,"stats":{"idleConnectionCount":0,"totalConnectionCount":1,"waitingRequestCount":0}},"message":"created a new client connection","sequence":2,"time":1622298366093,"version":"1.0.0"}
{"context":{"package":"slonik","poolId":"ndWsfTZoSseGAcqQuHCzzQ-0","logLevel":20,"processId":19123,"stats":{"idleConnectionCount":0,"totalConnectionCount":1,"waitingRequestCount":0}},"message":"client is checked out from the pool","sequence":3,"time":1622298366094,"version":"1.0.0"}
{"context":{"package":"slonik","poolId":"ndWsfTZoSseGAcqQuHCzzQ-0","logLevel":20,"processId":19123,"stats":{"idleConnectionCount":0,"totalConnectionCount":0,"waitingRequestCount":0}},"message":"client connection is closed and removed from the client pool","sequence":4,"time":1622298366101,"version":"1.0.0"}
TypeError: connectionHandler is not a function
    at /xxx/node_modules/.pnpm/slonik@23.7.0_pg-native@3.0.0/node_modules/slonik/src/binders/bindPool.ts:56:18
    at Object.createConnection (/xxx/node_modules/.pnpm/slonik@23.7.0_pg-native@3.0.0/node_modules/slonik/src/factories/createConnection.ts:152:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.init (/xxx/xxx/packages/orm/slonik/src/index.ts:17:16)
    at _default (/xxx/xxx/packages/cli/src/index.ts:54:7)
    at Object.cli (/xxx/xxx/packages/cli/src/cli.ts:7:3)
```

## Steps to Reproduce

A simple benchmarking script:

```js
let pool
let connection

async function init() {
  const connectionUri = databaseConfig.connectionString
  const clientConfiguration = {
    maximumPoolSize: databaseConfig.pool.maximumPoolSize,
    preferNativeBindings: true,
    captureStackTrace: false,
  }
  pool = createPool(connectionUri, clientConfiguration)
  connection = await pool.connect()
}

async function run() {
  for // run a bunch of times {
    await init()
    await query({pool, connection})
  }
}

run()
```

**Comment by vjpr** [comment]
This seems to be because I am not passing anything to `pool.connect`. Some validation and better message would fix this.

**Comment by gajus** [comment]
Safety checks are provided using TypeScript.
