### ISSUE TITLE
How to handle invalid UUID error in slonik?

### ISSUE THREAD

**Issue by MichaelGrigoryan25** [gajus/slonik#286]
Hi, there!

Recently I stumbled upon this error when trying to do some queries with slonik specifically with UUID. 

The error that I'm getting is:

```
error: invalid input syntax for type uuid: "fqwef23rf12rr1-r231rfeqfcqwecqwceqw"
```

I have made the id invalid on purpose. Is there an error type like `SlonikError` to handle this error in `catch (error) {...}` block? So far, I have tried using some error types like `SlonikError` and `InvalidInputError` but none of them seemed to match the one that I was getting.

Thanks a bunch!

Michael.

**Comment by gajus** [comment]
It should be `InvalidInputError`. If not, then it is a bug. Please create a test case showing this error.

Closing until there is a test case.

**Comment by MichaelGrigoryan25** [comment]
Hi @gajus , thanks for your response and sorry for not including the test case. 

Here's a simple test case:

```js
import { InvalidInputError, sql, createPool } from "slonik";

const db = createPool("postgresql://postgres:miki2005@localhost:5432/postgres");

try 
  db.query(sql`
    CREATE TABLE IF NOT EXISTS something (
        id         UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
        name    VARCHAR NOT NULL
    );
  `);

  db.query(sql`
    SELECT * FROM something WHERE id = '12345678';
  `);
} catch (error) {
  if (error instanceof InvalidInputError) {
    console.log`There was an error`;
  }
}
```

And here's the error

```
(node:18352) UnhandledPromiseRejectionWarning: error: invalid input syntax for type uuid: "regwe"
    at Parser.parseErrorMessage (C:\Users\...\Desktop\dd\node_modules\pg-protocol\src\parser.ts:369:69)
    at Parser.handlePacket (C:\Users\...\Desktop\dd\node_modules\pg-protocol\src\parser.ts:188:21)
    at Parser.parse (C:\Users\...\...\dd\node_modules\pg-protocol\src\parser.ts:103:30)
    at Socket.<anonymous> (C:\Users\...\Desktop\dd\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (events.js:376:20)
    at Socket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18352) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are 
not handled will terminate the Node.js process with a non-zero exit code.
```

Cheers!
Mike.

**Comment by gajus** [comment]
You are missing `await` in your code. It seems that's why you are getting `UnhandledPromiseRejectionWarning`.

**Comment by MichaelGrigoryan25** [comment]
Whoops, sorry my bad. The code should look like this and still nothing is getting logged in the console

```ts
import { InvalidInputError, sql, createPool } from "slonik";

const db = createPool("postgresql://postgres:miki2005@localhost:5432/postgres");

(async () => {
  try {
    await db.query(sql`
      CREATE TABLE IF NOT EXISTS something (
          id         UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
          name    VARCHAR NOT NULL
      );
    `);

    await db.query(sql`
      SELECT * FROM something WHERE id = '12345678';
    `);
  } catch (error) {
    if (error instanceof InvalidInputError) {
      console.log`There was an error`;
    }
  }
})();
```

It still doesn't log `There was an error`

**Comment by MichaelGrigoryan25** [comment]
Whoops, sorry, my bad!

The code is supposed to look like this, but still I get the same error

```ts
import { InvalidInputError, sql, createPool } from "slonik";

const db = createPool("postgresql://postgres:miki2005@localhost:5432/postgres");

(async () => {
  try {
    await db.query(sql`
      CREATE TABLE IF NOT EXISTS something (
          id         UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
          name    VARCHAR NOT NULL
      );
    `);

    await db.query(sql`
      SELECT * FROM something WHERE id = '12345678';
    `);
  } catch (error) {
    if (error instanceof InvalidInputError) {
      console.log`There was an error`;
    }
  }
})();
```

**Comment by MichaelGrigoryan25** [comment]
Whoops, sorry, my bad.

The code is supposed to be like this, but I still get the same error

```ts
import { InvalidInputError, sql, createPool } from "slonik";

const db = createPool("...");

(async () => {
  try {
    await db.query(sql`
      CREATE TABLE IF NOT EXISTS something (
          id         UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
          name    VARCHAR NOT NULL
      );
    `);

    await db.query(sql`
      SELECT * FROM something WHERE id = '12345678';
    `);
  } catch (error) {
    if (error instanceof InvalidInputError) {
      console.log`There was an error`;
    }
  }
})();
```

**Comment by gajus** [comment]
And you are still getting uncaught exception error?

**Comment by MichaelGrigoryan25** [comment]
Here, I should get a `There was an error` in the console but I don't. Only after adding an `else { console.error(error) }`, the error is shown and is an Uncaught Exception.

**Comment by MichaelGrigoryan25** [comment]
Any updates on this @gajus ?

**Comment by gajus** [comment]
It has been fixed in the latest Slonik version. Thank for sharing error reproduction.

**Comment by MichaelGrigoryan25** [comment]
Nice! Thank you :)
