### ISSUE TITLE
error: date/time field value out of range

### ISSUE THREAD

**Issue by michaelgrigoryan25** [gajus/slonik#291]
Hi! I'm trying to execute a query but can't seem to find a way to convert the date of this format `2021-08-15 15:21:47` from timestamp to itself again.

Here's my query:

```js
const { rows: nextPosts } = await slonik.query(sql`
    SELECT id FROM items WHERE id > ${lastItem.id!!} AND created_at > ${lastItem.created_at!!} 
    ORDER BY created_at DESC LIMIT ${Number(limit)};
`);
```

I get the `lastItem` from another query and I get a UNIX timestamp-like `created_at` field(e.g. 1234567890) instead of getting the actual date value.

I'm implementing cursor and date-based pagination. Here is the sample model:

```sql
CREATE TABLE IF NOT EXISTS items (
    id UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
    something VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
```

And here's the error that I'm getting:

```
error: date/time field value out of range: "1629026614116"
    at Parser.parseErrorMessage (C:\Users\something\Desktop\something\node_modules\pg-protocol\src\parser.ts:369:69)
    at Parser.handlePacket (C:\Users\something\Desktop\something\node_modules\pg-protocol\src\parser.ts:188:21)
    at Parser.parse (C:\Users\something\Desktop\something\node_modules\pg-protocol\src\parser.ts:103:30)
    at Socket.<anonymous> (C:\Users\something\Desktop\something\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 234,
  severity: 'ERROR',
  code: '22008',
  detail: undefined,
  hint: 'Perhaps you need a different "datestyle" setting.',
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'd:\\pginstaller_13.auto\\postgres.windows-x64\\src\\backend\\utils\\adt\\datetime.c',
  line: '3739',
  routine: 'DateTimeParseError',
  notices: []
```

Is there a way that I can get the actual date value from a query?

**Comment by michaelgrigoryan25** [comment]
Nevermind. Got it fixed by doing this:

```sql
TO_TIMESTAMP(${lastPost.created_at!!})::TIMESTAMP
```

**Comment by michaelgrigoryan25** [comment]
Sorry, It didn't work. Here's the output after doing `TO_TIMESTAMP(number)::TIMESTAMP`

```
53591-12-02 20:46:09.999872
```

**Comment by michaelgrigoryan25** [comment]
This might seem funny but this is the actual solution. You have to divide the timestamp by 1000.

```sql
TO_TIMESTAMP(number/1000)::TIMESTAMP
```
