### ISSUE TITLE
How to connect from App engine in a connection string?

### ISSUE THREAD

**Issue by Vasilisa119** [gajus/slonik#330]
I try to connect to database in google cloud from app engine to unix socket path. I used a guide [pg-connection-string](https://www.npmjs.com/package/pg-connection-string), but got error: 'SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string'. Url:

`socket://${process.env.USER}:${process.env.PASSWORD}@/cloudsql/my-project-999999:europe-west4:my-project?db=${process.env.DB}`

After I looked for a similar issue [here](https://github.com/gajus/slonik/discussions/290) and tried this solution, but I got the same error. I tried to used database IP in connection string and I was able to connect from local but still can't connect from app engine. I get error:  

`(node:19) UnhandledPromiseRejectionWarning: ConnectionError: Connection terminated due to connection timeout   at createConnection (/app/node_modules/slonik/dist/src/factories/createConnection.js:67:23)  at processTicksAndRejections (internal/process/task_queues.js:97:5)`

I tried these urls and always get the error "Connection terminated due to connection timeout" (they work when connection is remote to google cloud, but not work in App Engine):

socket://${process.env.USER}:${process.env.PASSWORD}@999.999.999.999:5432?db=${process.env.DB}
postgresql://${process.env.USER}:${process.env.PASSWORD}@999.999.999.999:5432?db=${process.env.DB}
postgresql://${process.env.USER}:${process.env.PASSWORD}@999.999.999.999:5432?db=${process.env.DB}
socket://${process.env.USER}:${process.env.PASSWORD}@999.999.999.999:5432?db=${process.env.DB}&ssl=1
socket://${process.env.USER}:${process.env.PASSWORD}@999.999.999.999:5432?db=${process.env.DB}&unix_socket=/cloudsql/${process.env.CONNECTION_NAME}

I also try used google tutorial, but [it uses knex and not connection string](https://cloud.google.com/sql/docs/postgres/connect-app-engine-flexible). 

What could be the problem? I will be very grateful for any help. 

My slonik v.27.0.0 (trying apply 26.0.0 - unsuccessfully), pg v.8.7.3, node v.16.13.0.

**Comment by Vasilisa119** [comment]
After many tries this connection string worked (I used PRIVATE_IP_DATABASE):

`socket://${process.env.SQL_USER}:${process.env.SQL_PASSWORD}@${process.env.IP_DB_PRIVATE}?db=${process.env.DB}`
