### ISSUE TITLE
Cannot use variable as name to create a new database using sql template literals

### ISSUE THREAD

**Issue by ehupin** [gajus/slonik#346]
## Expected Behavior
I would expect this code to run successfully so I can create a databasewith a name from a variable:
``` javascript
const uri = 'postgresql://postgres:postgres@localhost'
const pool = createPool(uri)

const dbName = 'my_database'
await pool.query(sql`CREATE DATABASE ${dbName}`)
```
## Current Behavior
The code fails and I have this error:

```javascript

/home/my_user/my_project/node_modules/pg-protocol/src/parser.ts:369
      name === 'notice' ? new NoticeMessage(length, messageValue) : new DatabaseError(messageValue, length, name)
                                                                    ^
error: syntax error at or near "$1"
    at Parser.parseErrorMessage (/home/my_user/my_project/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/home/my_user/my_project/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/home/my_user/my_project/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/home/my_user/my_project/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 91,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1176',
  routine: 'scanner_yyerror',
  notices: []
}

```
## Possible Solution
The name of the database can be hard coded, then it works, but it makes the code much less flexible.

**Comment by ehupin** [comment]
I realise it is not a `slonik` issue, but a `pg-protocol` one, so I'm closing the ticket here.
