### ISSUE TITLE
Should passing bad SQL to stream() throw an Error?

### ISSUE THREAD

**Issue by alxndrsn** [gajus/slonik#413]
Passing bad syntax to `pool.stream()` doesn't give any indication that something bad has been done.

## `psql`:

```
postgres=# NONSENSE NOT REALLY SQL;
ERROR:  syntax error at or near "NONSENSE"
LINE 1: NONSENSE NOT REALLY SQL;
        ^
```

## slonik's `.stream()`:

* doesn't throw
* returns `null` when `stream.read()` is called

Demo'd at: https://github.com/gajus/slonik/pull/414/files

**Comment by alxndrsn** [comment]
I think there is an Error thrown, but not handled - running the following in the node REPL:

```js
> q = pool.stream(sql`NONSENSE NOT REALLY SQL`, s => global.s = s)
Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 1594,
  [Symbol(trigger_async_id_symbol)]: 5,
  [Symbol(destroyed)]: { destroyed: false }
}
> Uncaught:
error: syntax error at or near "NONSENSE"
    at Parser.parseErrorMessage (/home/user/temp/slonik/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/user/temp/slonik/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/user/temp/slonik/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/user/temp/slonik/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:537:15)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  length: 96,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '1',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1176',
  routine: 'scanner_yyerror',
  notices: []
}
```

**Comment by alxndrsn** [comment]
Opened in error - the error is thrown asynchronously by `.stream()`.
