### ISSUE TITLE
Simple example?

### ISSUE THREAD

**Issue by retorquere** [gajus/slonik#43]
Is there a simple start-to-finish example somewhere? I tried the script below using typescript, but I'm getting `Cannot find name 'sql'`

```
import { createPool } from 'slonik'

const pool = createPool('postgres://')

function main(asyncMain) {
  asyncMain()
    .then(exitCode => {
      process.exit(exitCode || 0)
    })
    .catch(err => {
      console.log(err)
      process.exit(1)
    })
}

main(async () => {
  pool.connect(async (connection) => {
    console.log('hello')
    console.log(await connection.query(sql`SELECT 1`));
  });
})
```

Where should I specify my connection parameters BTW? Either a connectstring or host/username/etc?

**Comment by retorquere** [comment]
Ah wait, adding `sql` to the import git rid of that, but now it doesn't output anything so it doesn't look like it ever does the connect;

```
import { sql, createPool } from 'slonik'

const pool = createPool('postgres://')

function main(asyncMain) {
  asyncMain()
    .then(exitCode => {
      process.exit(exitCode || 0)
    })
    .catch(err => {
      console.log(err)
      process.exit(1)
    })
}

main(async () => {
  console.log(sql`SELECT 1`)
  pool.connect(async (connection) => {
    console.log('starting query')
    console.log(await connection.query(sql`SELECT 1`));
  });
})
```

outputs

```
{ sql: 'SELECT 1', type: Symbol(SLONIK_SQL), values: [] }
```

but nothing more
```

**Comment by retorquere** [comment]
(sorry for the frequent updates, I'm experimenting my way through this), I've gotten a little further; using this (config.json has connection info that I can use successfully to connect using node-postgres) I seem to get connected but then I get 

```
postgresql://<hostname>:3306/zotero?user=zotero1&password=<password>
{ sql: 'SELECT 1', type: Symbol(SLONIK_SQL), values: [] }
ConnectionError: password authentication failed for user "emile"
    at createConnection (/home/emile/github/zot2db/node_modules/slonik/src/factories/createConnection.js:61:11)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

`emile` is my local username, but it's not used anywhere in the connection info.

```
import { sql, createPool } from 'slonik'
const config = require('./config.json').aws

const connectString = `postgresql://${config.host}:${config.port}/${config.database}?user=${config.user}&password=${config.password}`
console.log(connectString
  .replace(config.password, '<password>')
  .replace(config.host, '<hostname>')
)

const pool = createPool(connectString)

function main(asyncMain) {
  asyncMain()
    .then(exitCode => {
      process.exit(exitCode || 0)
    })
    .catch(err => {
      console.log(err)
      process.exit(1)
    })
}

main(async () => {
  console.log(sql`SELECT 1`)
  await pool.connect(async (connection) => {
    console.log('starting query')
    console.log(await connection.query(sql`SELECT 1`));
  });
})
```

**Comment by retorquere** [comment]
got it: 

```
const connectString = `postgresql://${encodeURIComponent(config.user)}:${encodeURIComponent(config.password)}@${config.host}:${config.port}/${config.database}`
```

sorry for the noise.

**Comment by gajus** [comment]
```
`postgresql://${config.host}:${config.port}/${config.database}?user=${config.user}&password=${config.password}`

```

This looks fragile. I will add a connection URI builder.

https://github.com/gajus/slonik/issues/45
