### ISSUE TITLE
Unix domain socket connection string throws: [ERR_INVALID_URL]: Invalid URL

### ISSUE THREAD

**Issue by kimmobrunfeldt** [gajus/slonik#468]
When passing [unix domain socket](https://github.com/brianc/node-postgres/tree/4b229275cfe41ca17b7d69bd39f91ada0068a5d0/packages/pg-connection-string#unix-domain-sockets) connection string supported by pg internally, slonik throws an error:

```
TypeError [ERR_INVALID_URL]: Invalid URL at new NodeError (node:internal/errors:399:5) at URL.onParseError (node:internal/url:565:9) at new URL (node:internal/url:645:5) at parseDsn (/app/node_modules/slonik/dist/src/utilities/parseDsn.js:13:17) at createPoolConfiguration (/app/node_modules/slonik/dist/src/factories/createPoolConfiguration.js:8:56) at createPool (/app/node_modules/slonik/dist/src/factories/createPool.js:22:85) at getPool (/app/dist/src/db/slonik.js:19:42) at Server.<anonymous> (/app/dist/src/index.js:24:49) at Server.emit (node:events:513:28) at emitCloseNT (node:net:2135:8) at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  input: 'socket://user:pass@/cloudsql/project:europe-west3:service?db=my_db&encoding=utf8',
  code: 'ERR_INVALID_URL'
}
```

## Expected Behavior

Connection string is correctly passed, for example like this:

```typescript
var parse = require('pg-connection-string').parse;
var config = parse('socket://user:pass@/cloudsql/project:europe-west3:service?db=my_db&encoding=utf8')
```

## Current Behavior

Error is thrown.

## Possible Solution

These socket strings are a bit weird since they aren't valid real URLs, but they are the recommended way to connect to postgres in Google Cloud Run: https://cloud.google.com/sql/docs/postgres/connect-run#connect_to

## Steps to Reproduce

Open node in terminal and type:

```typescript
const slonik = require('slonik')
slonik.createPool('socket://user:pass@/cloudsql/project:europe-west3:service?db=my_db&encoding=utf8')
```

**Comment by kimmobrunfeldt** [comment]
I was able to find a workaround! 


```typescript
function getConnectionUrl(databaseUrl: string): string {
  if (!databaseUrl.startsWith('socket:')) {
    return databaseUrl
  }
  const config = parse(databaseUrl)
  const url = new URL(
    `postgresql://${config.user}:${config.password}@${encodeURIComponent(
      config.host!
    )}/${config.database}`
  )
  return url.toString()
}

const pool = await createPool(getConnectionUrl(environment.databaseUrl))
```

With that setup, I can keep using regular `postgresql://user:pass@localhost:5432/dbname` locally, while using the `socket:` protocol format in production

**Comment by EgertV** [comment]
Got it working by encoding the path.
```javascript
const socketPath = encodeURIComponent('/var/run/postgresql');

createPool(`socket://my_user@${socketPath}/my_database`)
````
Note that socket itself `.s.PGSQL.5432` is left out because otherwise the path will resolve to `/var/run/postgresql/.s.PGSQL.5432/.s.PGSQL.5432`.
I believe it's because node-postgres library appends it when the path starts with `/`.
See https://github.com/brianc/node-postgres/blob/65ca2458fd0079f36a99a7752a7931483cd57ed6/packages/pg/lib/client.js#L111

**Comment by gajus** [comment]
This is by design, as it is documented in https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING-URIS

> The host part is interpreted as described for the parameter [host](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-HOST). In particular, a Unix-domain socket connection is chosen if the host part is either empty or looks like an absolute path name, otherwise a TCP/IP connection is initiated. Note, however, that the slash is a reserved character in the hierarchical part of the URI. So, to specify a non-standard Unix-domain socket directory, either omit the host part of the URI and specify the host as a named parameter, or percent-encode the path in the host part of the URI:
> 
> ```
> postgresql:///dbname?host=/var/lib/postgresql
> postgresql://%2Fvar%2Flib%2Fpostgresql/dbname
> ```
