### ISSUE TITLE
Pool is missing error handling

### ISSUE THREAD

**Issue by valeneiko** [gajus/slonik#471]
If existing pool connection is terminated by the server, PgPool will emit `error` event. Slonik does not register a listener for that event, so it results in a crash instead. It can happen in case of DB failover, or if someone runs `pg_terminate_backend(...)` query.

`PgPool` is `EventEmitter` which can emit `error` events, which by default crash node process: [docs](https://nodejs.org/docs/latest-v18.x/api/events.html#error-events).

## Expected Behavior
Error is logged and ignored.

## Current Behavior
If `PgPool` emits `error` event, node crashes : [docs](https://nodejs.org/docs/latest-v18.x/api/events.html#error-events).

## Possible Solution
- Immediately after a `pool` is created, register `error` event listener to log the error.
  ```ts
  // https://github.com/gajus/slonik/blob/main/src/factories/createPool.ts#L80-L85
  pool.on('error', (error) => {
    poolLog.error({
      error: serializeError(error),
    }, 'client error');
  });
  ```
- Do the same for the `setupClient`:
  ```ts
  // https://github.com/gajus/slonik/blob/main/src/factories/createPool.ts#L61-L69
  setupClient.on('error', (error) => {
    poolLog.error({
      error: serializeError(error),
    }, 'setup client error');
  });
  ```

## Steps to Reproduce
1. Create slonik pool, establish a few connections and wait
   ```ts
   const pool = await createPool(...);
   await Promise.all(new Array(10).fill(null).map(() => pool.connect(() => Promise.resolve())));
   await setTimeout(10000);
   ```
2. Run the SQL query to terminate all connections (or crash the DB)
   ```sql
   SELECT *, pg_terminate_backend(pid)
   FROM pg_stat_activity
   WHERE pid != pg_backend_pid()
   ```
3. Observe process started in step1 crashed

**Comment by gajus** [comment]
I am not able to replicate this issue @valeneiko 

https://github.com/gajus/slonik/pull/507

Based on the description, I would expect this test to fail somehow, but it is passing as expected.

https://github.com/gajus/slonik/pull/507/files#diff-87a6820c951329f6ddf0055e0afd4f289f3be2a0bd147d7dccab62657e0d699bR175

**Comment by valeneiko** [comment]
I have just tried this script (a copy of your test) and got the exception + crash:
```js
import { setTimeout as delay } from 'timers/promises';
import { createPool, sql } from 'slonik';

async function main() {
  process.on('uncaughtExceptionMonitor', (err) => {
    console.log(
      '\n\n==================================== UNCAUGHT EXCEPTION ====================================\n\n',
      err,
      '\n\n============================================================================================\n\n',
    );
  });

  const pool = await createPool(
    'postgres://postgres:postgres@postgres:5432/postgres',
  );

  let targetPid;

  setTimeout(() => {
    if (!targetPid) {
      throw new Error('Expected target PID to be set');
    }

    console.log('terminatinating active backend %s', targetPid);

    void pool.query(sql.unsafe`
      SELECT pg_terminate_backend(${targetPid})
    `);
  }, 200);

  let targetQuery;

  await pool.connect(async (connection) => {
    targetPid = await connection.oneFirst(sql.unsafe`
      SELECT pg_backend_pid()
    `);

    await delay(1_000);

    targetQuery = connection.query(sql.unsafe`
      SELECT 1
    `);
  });
}

void main();
```

Here is the output:
```js
terminatinating active backend 84


==================================== UNCAUGHT EXCEPTION ====================================

 Error: Client has encountered a connection error and is not queryable
    at /workspace/node_modules/.pnpm/pg@8.11.3/node_modules/pg/lib/client.js:526:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /workspace/node_modules/.pnpm/slonik@35.0.1_zod@3.22.2/node_modules/slonik/dist/connectionMethods/query.js:8:24
    at async executeQuery (/workspace/node_modules/.pnpm/slonik@35.0.1_zod@3.22.2/node_modules/slonik/dist/routines/executeQuery.js:126:26)
    at async query (/workspace/node_modules/.pnpm/slonik@35.0.1_zod@3.22.2/node_modules/slonik/dist/connectionMethods/query.js:6:12) {
  notices: []
} 

============================================================================================
```


Maybe the test framework you are using silences uncaught exceptions?

**Comment by gajus** [comment]
> Maybe the test framework you are using silences uncaught exceptions?

In your example, you are not handling `targetQuery` promise rejection.

```diff
    targetQuery = connection.query(sql.unsafe`
      SELECT 1
-    `);
+.   `).catch((error) => { console.log('error', error) });
```

That will prevent the undesired behavior.

**Comment by valeneiko** [comment]
Yup, my bad. Missed that.

Here is the script that actually crashes:
```js
import { createPool, sql } from 'slonik';

async function main() {
  process.on('uncaughtExceptionMonitor', (err) => {
    console.log(
      '\n\n==================================== UNCAUGHT EXCEPTION ====================================\n\n',
      err,
      '\n\n============================================================================================\n\n',
    );
  });

  const pool = await createPool(
    'postgres://postgres:postgres@postgres:5432/postgres',
  );
  await Promise.all(
    new Array(2).fill(null).map(() => pool.connect(() => Promise.resolve())),
  );

  await pool
    .query(
      sql.unsafe`
    SELECT *, pg_terminate_backend(pid)
    FROM pg_stat_activity
    WHERE pid != pg_backend_pid()`,
    )
    .catch(() => {});
}

void main();
```

Looks like it is idle connections that cause it.

**Comment by gajus** [comment]
Thank you!

**Comment by gajus** [comment]
Note that this didn't address `setupClient`. I will try to add a test for it too.
