### ISSUE TITLE
How to use `WHERE id IN` / `WHERE id = ANY` with v34+?

### ISSUE THREAD

**Issue by coolaj86** [gajus/slonik#498]
I've read https://github.com/gajus/slonik/issues/430 and a few others, but I can't get past various errors.

- `error: input of anonymous composite types is not implemented`
- `error: type "varchar(26)[]" does not exist`
- `error: operator does not exist: id = character varying`
- `error: op ANY/ALL (array) requires array on right side`

Here's what I've tried. What do I need to do?

## WHERE id IN(ids)

```js
let idsArr = ["01H59975E0VEVDM7YJ11AY4B79"];
let ids = sql.join(idsArr, sql.fragment`, `);
sql.unsafe`
  SELECT id
  FROM foo
  WHERE id IN (${ids})
`;
```

```text
error: input of anonymous composite types is not implemented
    at /home/app/node_modules/pg/lib/client.js:526:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/app/node_modules/slonik/dist/connectionMethods/query.js:8:24
    at async executeQuery (/home/app/node_modules/slonik/dist/routines/executeQuery.js:126:26)
    at async query (/home/app/node_modules/slonik/dist/connectionMethods/query.js:6:12)
    at async /home/app/node_modules/slonik/dist/binders/bindPool.js:96:24
    at async createConnection (/home/app/node_modules/slonik/dist/factories/createConnection.js:110:18)
    at async Object.query (/home/app/node_modules/slonik/dist/binders/bindPool.js:95:20)
```

## WHERE id = ANY(ids)

```js
let idsArr = ["01H59975E0VEVDM7YJ11AY4B79"];
let ids = sql.array(idsArr, 'varchar(26)');
// let ids = sql.array(idsArr, sql.fragment`'varchar(26)[]'`);
sql.unsafe`
  SELECT id
  FROM foo
  WHERE id = ANY(${ids})
`;
```

```text
error: type "varchar(26)[]" does not exist
    at /home/app/node_modules/pg/lib/client.js:526:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/app/node_modules/slonik/dist/connectionMethods/query.js:8:24
    at async executeQuery (/home/app/node_modules/slonik/dist/routines/executeQuery.js:126:26)
    at async query (/home/app/node_modules/slonik/dist/connectionMethods/query.js:6:12)
    at async /home/app/node_modules/slonik/dist/binders/bindPool.js:96:24
    at async createConnection (/home/app/node_modules/slonik/dist/factories/createConnection.js:110:18)
    at async Object.query (/home/app/node_modules/slonik/dist/binders/bindPool.js:95:20)
```

**Comment by dantio** [comment]
That works for me:
```
WHERE id IN (${sql.join(ids, sql.fragment`,`)})
```

**Comment by gajus** [comment]
```ts
sql.array(idsArr, sql.fragment`varchar(26)`)
```

**Comment by gajus** [comment]
It is documented here https://github.com/gajus/slonik#sqlarray-membertype
