### ISSUE TITLE
Support pgvector

### ISSUE THREAD

**Issue by gajus** [gajus/slonik#511]
https://github.com/pgvector/pgvector-node/#pgvector-node

**Comment by jimlloyd** [comment]
This must be why I have not been able to make progress after my first few hours with `slonik`.

I create a table with 
```
        await pool.connect(async connection =>
        {
            // We just created a new database so we do not need `IF NOT EXISTS` for any of these entities
            await connection.query(sql.unsafe`CREATE EXTENSION vector`);

            /// MEM CONTENT
            await connection.query(sql.unsafe`CREATE TABLE mem(
                id BIGINT PRIMARY KEY,     -- bun.hash
                content TEXT NOT NULL,
                embed_vector vector(768) NOT NULL,
                tssearch tsvector GENERATED ALWAYS AS (to_tsvector('english', content)) STORED,
                tokens INT NOT NULL)`
            );
     }
```

And then I try to insert data with
```
async function createMem(content: string) : Promise<Mem> {
    const mem: Mem = Mem.parse({
        id: BigInt(Bun.hash(content)),
        content: content,
        embed_vector: await embedding.generateOne(content),
        tokens: count_tokens(content)
    })
    return mem;
}

    return await pool.connect(async connection => {
        // A Mem is entirely determined from its content, so we only pass in the content to this function,
        // and then construct the Mem from the content.
        const mem: Mem = await createMem(content);

        try {
            const insertMemQuery = sql.type(Mem)`
                INSERT INTO mem (id, content, embed_vector, tokens)
                VALUES (${mem.id}, ${mem.content}, ${mem.embed_vector}, ${mem.tokens})`;

            await connection.query(insertMemQuery);
            // TODO validate result
        } catch (err) {
            console.error((err as Error).stack)
            throw err;
        }
```

I get this error: 


```
Error: Expected token to include "type" property.
    at isSqlToken (/Users/jim.lloyd/hub/Memento/node_modules/slonik/dist/utilities/isSqlToken.js:29:14)
    at createFragment (/Users/jim.lloyd/hub/Memento/node_modules/slonik/dist/factories/createSqlTag.js:39:22)
    at <anonymous> (/Users/jim.lloyd/hub/Memento/node_modules/slonik/dist/factories/createSqlTag.js:135:20)
    at <anonymous> (/Users/jim.lloyd/hub/Memento/src/lib/postgresdb.ts:127:30)
    at asyncFunctionResume (native)
    at promiseReactionJobWithoutPromiseUnwrapAsyncContext (native)
    at promiseReactionJob (native)
    at processTicksAndRejections (native)
UnexpectedStateError: Expected token to include "type" property.
```

`pgvector` is a requirement for the app I want to build. `slonik` looks very cool but perhaps I have to find some other alternative? Is there a workaround until this issue is addressed?

**Comment by gajus** [comment]
`pgvector` does support Slonik.

https://github.com/pgvector/pgvector-node/?tab=readme-ov-file#slonik
