### ISSUE TITLE
Automatically handle "remaining connection slots are reserved for non-replication superuser connections" error

### ISSUE THREAD

**Issue by gajus** [gajus/slonik#68]
When there are no connection slots available, `pool.connect()` fails with:

```json
{
  "name": "ConnectionError",
  "stack": "ConnectionError: remaining connection slots are reserved for non-replication superuser connections\n    at createConnection (/srv/node_modules/slonik/dist/factories/createConnection.js:36:11)\n    at processTicksAndRejections (internal/process/task_queues.js:89:5)",
  "message": "remaining connection slots are reserved for non-replication superuser connections"
}

```

This is almost never desirable.

The desirable behaviour is to at least retry connection multiple times.

**Comment by gajus** [comment]
This would just mask the underlying issue.
